# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh. DO NOT EDIT.
class Downprint < Formula
  desc "Convert Markdown to PDF with GitHub-like styling via headless Chrome"
  homepage "https://github.com/sorokin-vladimir/downprint"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorokin-vladimir/downprint/releases/download/v1.0.0/downprint_darwin_amd64.tar.gz"
      sha256 "a825b494d6ad61b99ba9f9b2c077ddc644462747eed474e973ff0a485aae0c56"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorokin-vladimir/downprint/releases/download/v1.0.0/downprint_darwin_arm64.tar.gz"
      sha256 "bac854e1472e1e50c1c2a61a21c3ee52dae77477efded407a23b6adf4cc7b11f"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/downprint/releases/download/v1.0.0/downprint_linux_amd64.tar.gz"
      sha256 "4a1305838060520d834d3610a0c54b809cbf095ca00def0b60edbf706ef26c27"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/downprint/releases/download/v1.0.0/downprint_linux_arm64.tar.gz"
      sha256 "559c2a85b0809e10bacadbf45eb710a8b47558fa1d1fd7aec9249d71a5fb04f4"
    end
  end

  def install
    bin.install "downprint"
  end

  # A formula cannot depend on a cask, so the browser is left to the user.
  def caveats
    <<~EOS
      downprint needs Google Chrome or Chromium at runtime:
        brew install --cask google-chrome
      To use a browser outside the standard locations, set DOWNPRINT_CHROME
      or pass -chrome /path/to/browser.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/downprint -version")
  end
end
