# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh. DO NOT EDIT.
class Tele < Formula
  desc "TUI Telegram client"
  homepage "https://github.com/sorokin-vladimir/tele"
  version "1.11.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.11.10/tele_darwin_amd64.tar.gz"
      sha256 "14208163667c436e1d2ff1d7a98734bf423f49bec7faee568e24e92ff80476c2"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.11.10/tele_darwin_arm64.tar.gz"
      sha256 "341303c482742aa88bfd19e9ca1968df79f3e7fcf59f8787b2883f85ea1bea34"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.11.10/tele_linux_amd64.tar.gz"
      sha256 "82cf268d23a6ed295da661b3b06586757b4a684fafe68549e7a7e69c60a600aa"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.11.10/tele_linux_arm64.tar.gz"
      sha256 "560d2c885116d6c3ef8cf63f8bf4607534fe5cadd0a0aa37449d0982aceb0503"
    end
  end

  def install
    bin.install "tele"
  end

  test do
    system "#{bin}/tele", "--version"
  end
end