# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh. DO NOT EDIT.
class TeleBeta < Formula
  desc "TUI Telegram client (beta channel)"
  homepage "https://github.com/sorokin-vladimir/tele"
  version "1.8.1-beta.2"
  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.8.1-beta.2/tele_darwin_amd64.tar.gz"
      sha256 "f1384e38f424b37b5ac032dee071b47fc4583fc3f2be6304fd26bb10f3cf520d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.8.1-beta.2/tele_darwin_arm64.tar.gz"
      sha256 "3e3d0f6abed369b671eab6a2fc2d0829d0a50cfc74eecf6b9081d1c26859887c"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.8.1-beta.2/tele_linux_amd64.tar.gz"
      sha256 "3e87bbce80abb4ae07fe72689ee016a517a4af4e1e713b425912d80c8f4ed4cd"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.8.1-beta.2/tele_linux_arm64.tar.gz"
      sha256 "de7310c225b226ae40a7919003aa267ccc8365b3535667d1b4834c64df0f2e47"
    end
  end

  def install
    bin.install "tele" => "tele-beta"
  end

  test do
    system "#{bin}/tele-beta", "--version"
  end
end