# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh. DO NOT EDIT.
class TeleBeta < Formula
  desc "TUI Telegram client (beta channel)"
  homepage "https://github.com/sorokin-vladimir/tele"
  version "1.11.11-beta.4"
  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.11.11-beta.4/tele_darwin_amd64.tar.gz"
      sha256 "67db3af57aa8be8d827d0214df833ab696d497920e06bfb48d7ff1b2d69cda7c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.11.11-beta.4/tele_darwin_arm64.tar.gz"
      sha256 "2ceaf41b38c4f3dd3c6494a405b06a5123ccdca4b178c883a542638cbacc0a98"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.11.11-beta.4/tele_linux_amd64.tar.gz"
      sha256 "e61fc702f91e1890079afd1d0b8210cfaf5a4654d160afa6eb359ad2ef88a8df"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.11.11-beta.4/tele_linux_arm64.tar.gz"
      sha256 "fc2f5d1965274162006cc5094e4e0fefd37184017848d0a19cda1f8f71bc7868"
    end
  end

  def install
    bin.install "tele" => "tele-beta"
  end

  test do
    system "#{bin}/tele-beta", "--version"
  end
end